; PlatformIO Project Configuration File

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
extra_scripts = pre:scripts/git_version.py

monitor_speed = 115200

board_build.partitions = partitions.csv

lib_deps =
    handmade0octopus/ESP32-TWAI-CAN@^1.0.1
